#!/bin/bash
#make this an argument l8r
DBNAME=TEST
# Defining my database first table (EXAMPLE)

STRUCTURE0="CREATE TABLE COMPANY(
   ID INTEGER PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL,
   ADDRESS        CHAR(50),
   SALARY         REAL
);";

STRUCTURE1="CREATE TABLE RESTAURANT(
   ID INTEGER PRIMARY KEY     NOT NULL,
   NAME TEXT NOT NULL,
   ADDRESS TEXT NOT NULL,
   OWNERID INT NOT NULL,
   PERSONINCHARGE TEXT NOT NULL,
   FOREIGN KEY(OWNERID) references OWNER(ID),
   FOREIGN KEY(ID) references RESTAURANTINSPECTIONS(RESTAURANTID)
);";
STRUCTURE2="CREATE TABLE SEPTIC(
    ID INTEGER PRIMARY KEY     NOT NULL,
    OWNERID INT NOT NULL,
    FOREIGN KEY(ID) references SYSTEMPUMPINGRECORD(SEPTICID),
    FOREIGN KEY(ID) references SEPTICINSPECTIONS(SEPTICID),
    FOREIGN KEY(OWNERID) references OWNER(ID)
);";
STRUCTURE3="CREATE TABLE WELL(
    ID INTEGER PRIMARY KEY     NOT NULL,
    OWNERID INT NOT NULL,
    FOREIGN KEY(ID) references WATERQUALITYREPORT(WELLID),
    FOREIGN KEY(OWNERID) references OWNER(ID)
);";
STRUCTURE4="CREATE TABLE OWNER(
   ID INTEGER PRIMARY KEY     NOT NULL,
   OWNERNAME TEXT       NOT NULL,
   TELEPHONENUMBER TEXT NOT NULL
);";
STRUCTURE5="CREATE TABLE PROPERTY(
   ID INTEGER PRIMARY KEY     NOT NULL,
   GPSCOORDINATES REAL NOT NULL,
   ADDRESS TEXT NOT NULL,
   TOWN TEXT NOT NULL,
   STATE TEXT NOT NULL,   
   ZIPCODE INT NOT NULL,
   PLOTNUMER INT NOT NULL
);";

STRUCTURE6="CREATE TABLE RESTAURANTINSPECTIONS(
    ID INTEGER PRIMARY KEY     NOT NULL,
    RESTAURANTID INT NOT NULL,
    INSPECTOR TEXT NOT NULL,
    RISKLEVEL TEXT NOT NULL,
    HACCP INTEGER NOT NULL,
    TIMEIN INTEGER NOT NULL,
    TIMEOUT INTEGER NOT NULL,
    TYPEOFOPERATION INTEGER NOT NULL,
    TYPEOFINSPECTION INTEGER NOT NULL,
    PREVIOUSINSPECTIONDATE INTEGER,
    REASONING INTEGER NOT NULL,
    OTHERREASONING TEXT,
    MANAGEMENTANDPERSONNEL TEXT,
    FOODANDFOODPROTECTION TEXT,
    EQUIPMENTANDUTENSILS TEXT,
    WATERPLUMBINGANDWASTE TEXT,
    PHYSICALFACILITY TEXT,
    POISONOUSORTOXICMATERIALS TEXT,
    SPECIALREQUIREMENTS TEXT,
    OTHER0 TEXT,
    DISCUSSIONWITHPERSONINCHARGE TEXT,
    CORRECTIVEACTIONREQUIRED INT,
    VOLUNTARYCOMPLIANCE INT,
    REINSPECTIONSCHEDULED INT,
    VOLUNTARYDISPOSAL INT,
    EMPLOYEERESTRICTIONEXCLUSION INT,
    EMERGENCYSUSPENSION INT,
    EMERGENCYCLOSURE INT,
    OTHER1 INT,
    ADDITIONALNOTES TEXT,
    FOREIGN KEY(TYPEOFOPERATION) REFERENCES TYPEOFOPERATION(ID),
    FOREIGN KEY(TYPEOFINSPECTION) REFERENCES TYPEOFINSPECTION(ID),
    FOREIGN KEY(REASONING) REFERENCES REASONING(ID),
    FOREIGN KEY(ID) REFERENCES VIOLATIONS(RESTAURANTINSPECTIONID)   
);";
SUBSTRUCTURE60="CREATE TABLE TYPEOFOPERATION(
    ID INTEGER PRIMARY KEY     NOT NULL,
    OPERATIONTYPE TEXT NOT NULL
);";
SUBSTRUCTURE61="CREATE TABLE TYPEOFINSPECTION(
    ID INTEGER PRIMARY KEY     NOT NULL,
    INSPECTIONTYPE TEXT NOT NULL
);";
SUBSTRUCTURE62="CREATE TABLE REASONING(
    ID INTEGER PRIMARY KEY     NOT NULL,
    REASONING TEXT NOT NULL
);";




   #STATIC COMPONENT TABLE
STRUCTURE7="CREATE TABLE SYSTEMPUMPINGRECORD(
   ID INTEGER PRIMARY KEY     NOT NULL,
   SEPTICID INT NOT NULL,
   PUMPINGDATE REAL NOT NULL,
   QUANTITYPUMPED REAL NOT NULL,
   SYSTEMQUALITYOTHER TEXT NOT NULL,
   EFFLUENTTEEFILTERPRESENT INT NOT NULL,
   IFYESWASITCLEANED INT NOT NULL,
   OBSERVEDCONDITION TEXT NOT NULL,
   SYSTEMPUMPEDBYNAME TEXT NOT NULL,
   SYSTEMPUMPEDBYLICENSE TEXT NOT NULL,
   SYSTEMPUMPEDBYCOMPANY TEXT NOT NULL,
   LOCATIONWHERECONTENTSWEREDISPOSED TEXT NOT NULL,
   HAULER TEXT NOT NULL,
   HAULERDATE TEXT NOT NULL,
   RECEIVINGFACILITY TEXT NOT NULL,
   RECEIVINGFACILITYDATE TEXT NOT NULL,
   FOREIGN KEY(SEPTICID) references SEPTIC(ID)
);";

SUBSTRUCTURE63="CREATE TABLE SEPTICPUMPINGRECORD(
   ID INTEGER PRIMARY KEY     NOT NULL,
   OPTION TEXT NOT NULL
);";


STRUCTURE9="CREATE TABLE VIOLATIONS(
   ID INTEGER PRIMARY KEY     NOT NULL,
   RESTAURANTINSPECTIONID INT NOT NULL,
   CODEREFERENCE TEXT NOT NULL,
   CRITICALORREDITEM TEXT NOT NULL,
   DESCRIPTIONOFVIOLATIONCORRECTIONPLAN TEXT NOT NULL,
   DATEVERIFIED TEXT NOT NULL,
   FOREIGN KEY(RESTAURANTINSPECTIONID) references RESTAURANTINSPECTIONS(ID)
);";

STRUCTURE10="CREATE TABLE PRIVILEGES(
   ID INTEGER PRIMARY KEY     NOT NULL,
   PRIVILEGELEVEL INT NOT NULL,
   USERID INT NOT NULL,
   FOREIGN KEY(USERID) references USER(ID)
);";

#Salt field?
STRUCTURE11="CREATE TABLE USER(
   ID INTEGER PRIMARY KEY     NOT NULL,
   USERNAME TEXT NOT NULL,
   PASSWORDHASH NOT NULL,
   FOREIGN KEY(ID) references SAVEDSEARCHES(USERID),
   FOREIGN KEY(ID) references PRIVILEGES(USERID)
);";
STRUCTURE12="CREATE TABLE SAVEDSEARCHES(
   ID INTEGER PRIMARY KEY     NOT NULL,
   USERID INT NOT NULL,
   SAVEDSEARCH TEXT NOT NULL,
   FOREIGN KEY(USERID) references USER(ID)
);";

#Are we using epoch time or string for the date?
STRUCTURE13="CREATE TABLE WATERQUALITYREPORT(
   ID INTEGER PRIMARY KEY     NOT NULL,
   WELLID INT NOT NULL,
   CLIENTNAME TEXT NOT NULL,
   COLLECTEDBY TEXT NOT NULL,
   PROJECTNAME TEXT NOT NULL,
   PROJECTNUMBER TEXT NOT NULL,
   DATECOLLECTED INT NOT NULL,
   SAMPLEIDENTIFICATION TEXT NOT NULL,
   LABNUMBER REAL NOT NULL,
   TOTALCOLIFORMBACTERIA REAL NOT NULL,
   TOTALCOLIFORMBACTERIAUNITS TEXT NOT NULL,
   NITRATENITROGEN REAL NOT NULL,
   NITRATENITROGENUNITS TEXT NOT NULL,
   PH REAL NOT NULL,
   PHUNITS TEXT NOT NULL,
   IRON REAL NOT NULL,
   IRONUNITS TEXT NOT NULL,
   HARDNESSASCACO3 REAL NOT NULL,
   HARDNESSASCACO3UNITS TEXT NOT NULL,
   SULFATESULFUR REAL NOT NULL,
   SULFATESULFUREUNITS TEXT NOT NULL,
   CHLORIDE REAL NOT NULL,
   SPECIFICCONDUCTANCE REAL NOT NULL,
   SPECIFICCONDUCTANCEUNITS TEXT NOT NULL,
   THISWATERSAMPLEPASSESDRINKINGWATERSTANDARDS INT NOT NULL,
   SUBMITTEDBY TEXT NOT NULL,
   ADDITIONALNOTES TEXT,
   FOREIGN KEY(WELLID) references WELL(ID)
);";

STRUCTURE14="CREATE TABLE SEPTICINSPECTION(
   ID INTEGER PRIMARY KEY NOT NULL,
   NAMEOFINSPECTOR TEXT NOT NULL,
   COMPANYNAME TEXT NOT NULL,
   COMPANYADDRESS TEXT NOT NULL,
   CITY TEXT NOT NULL,
   STATE TEXT NOT NULL,
   ZIPCODE INTEGER NOT NULL,
   TELEPHONENUMBER TEXT NOT NULL,
   LICENSENUMBER TEXT NOT NULL,
   DEPAPPROVAL INTEGER NOT NULL,
   SYSTEMPASSES INTEGER,
   SYSTEMPASSESCOMMENTS TEXT,
   SYSTEMCONDITIONALLYPASSES INTEGER,
   SYSTEMCONDITIONALLYPASSESWILLPASSIFREPLACED INTEGER,
   SYSTEMCONDITIONALLYPASSESCOMMENTS TEXT,
   SYSTEMCONDITIONALLYPASSESALARMS INTEGER,
   SYSTEMCONDITIONALLYPASSESSEWAGE INTEGER,
   SYSTEMCONDITIONALLYPASSESSEWAGEPIPE INTEGER,
   SYSTEMCONDITIONALLYPASSESSEWAGEPIPECOMMENTS TEXT,
   SYSTEMCONDITIONALLYPASSESSEWAGEOBSTRUCTION INTEGER,
   SYSTEMCONDITIONALLYPASSESSEWAGEOBSTRUCTIONCOMMENTS TEXT,
   SYSTEMCONDITIONALLYPASSESSEWAGEDISTRIBUTION INTEGER,
   SYSTEMCONDITIONALLYPASSESSEWAGEDISTRIBUTIONCOMMENTS TEXT,
   SYSTEMCONDITIONALLYPASSESFOURPUMPS INTEGER,
   SYSTEMCONDITIONALLYPASSESFOURPUMPSPIPE INTEGER,
   SYSTEMCONDITIONALLYPASSESFOURPUMPSPIPECOMMENTS TEXT,
   SYSTEMCONDITIONALLYPASSESFOURPUMPSOBSTRUCTION INTEGER,
   SYSTEMCONDITIONALLYPASSESFOURPUMPSOBSTRUCTIONCOMMENTS TEXT,
   FURTHEREVALUATION INTEGER,
   FURTHEREVALUATIONSYSTEMWILLPASSIF INTEGER,
   FURTHEREVALUATIONSYSTEMWILLFAILIF INTEGER,
   FURTHEREVALUATIONFIFTYTOONEHUNDRED INTEGER,
   FURTHEREVALUATIONMETHODUSEDTODETERMINE TEXT,
   FURTHEREVALUATIONCOMMENTS TEXT
   SYSTEMFAILUREBACKUP INTEGER,
   SYSTEMFAILUREDISCHARGE INTEGER,
   SYSTEMFAILURESTATICLIQUID INTEGER,
   SYSTEMFAILURELIQUIDDEPTH INTEGER,
   SYSTEMFAILUREREQUIREDPUMPING INTEGER,
   SYSTEMFAILUREBELOWHIGHGROUNDWATER INTEGER,
   SYSTEMFAILURESURFACEWATERSUPPLY INTEGER,
   SYSTEMFAILUREPUBLIC INTEGER,
   SYSTEMFAILUREPRIVATE INTEGER,
   SYSTEMFAILUREPRIVATEGREATER INTEGER,
   SYSTEMFAILUREGPD INTEGER,
   SYSTEMFAILUREFORREAL INTEGER,
   LARGESYSTEMSSURFACEDRINKING INTEGER,
   LARGESYSTEMSTRIBUTARY INTEGER,
   LARGESYSTEMSNITROGEN INTEGER,
   CHECKLISTINFORMATIONPROVIDED INTEGER,
   CHECKLISTPUMPEDOUTTWOWEEKS INTEGER,
   CHECKLISTNORMALFLOW INTEGER,
   CHECKLISTLARGEVOLUMESINTRODUCED INTEGER,
   CHECKLISTPLANSEXAMINED INTEGER,
   CHECKLISTBACKUPINSPECTED INTEGER,
   CHECKLISTBREAKOUTINSPECTED INTEGER,
   CHECKLISTCOMPONENTSONSITE INTEGER,
   CHECKLISTINTERIORINSPECTION INTEGER,
   CHECKLISTFACILITYOWNER INTEGER,
   CHECKLISTEXISTINGINFORMATION INTEGER,
   CHECKLISTDETERMINED INTEGER,
   RESIDENTIALBEDROOMSDESIGN INTEGER,
   RESIDENTIALBEDROOMSACTUAL INTEGER,
   RESIDENTIALDESIGNFLOW INTEGER,
   RESIDENTIALCOMMENTS TEXT,
   RESIDENTIALRESIDENTS INTEGER,
   RESIDENTIALGARBAGEGRINDER INTEGER,
   RESIDENTIALLAUNDRYSEPARATE INTEGER,
   RESIDENTIALLAUNDRYINSPECTION INTEGER,
   RESIDENTIALSEASONALUSE INTEGER,
   RESIDENTIALWATERMETERREADINGS INTEGER,
   RESIDENTIALWATERMETERCOMMENTS TEXT,
   RESIDENTIALSUMPPUMP INTEGER,
   RESIDENTIALDATEOFOCCUPANCY INTEGER,
   COMMERCIALTYPE TEXT,
   COMMERCIALDESIGNFLOW INTEGER,
   COMMERCIALBASISOFDESIGNFLOW TEXT,
   COMMERCIALGREASETRAP INTEGER,
   COMMERCIALINDUSTRIALWASTE INTEGER,
   COMMERCIALWASTEDISCHARGE INTEGER,
   COMMERCIALWATERMETERREADINGS TEXT,
   COMMERCIALDATEOFOCCUPANCY INTEGER,
   COMMERCIALCOMMENTS TEXT,
   GENERALSOURCE TEXT,
   GENERALPUMPED INTEGER,
   GENERALVOLUMEPUMPED INTEGER,
   GENERALQUANTITYDETERMINED TEXT,
   GENERALREASONFORPUMPED TEXT
   GENERALTYPEOFSYSTEM INTEGER,
   GENERALTYPEOFSYSTEMCOMMENT TEXT,
   GENERALCOMPONENTAGE INTEGER,
   GENERALCOMPONENTDATE INTEGER,
   GENERALCOMPONENTSOURCE TEXT,
   GENERALSEWAGEODORS INTEGER,
   BUILDINGSEWERDEPTHBELOWGRADE INTEGER,
   BUILDINGSEWERMATERIAL INTEGER,
   BUILDINGSEWERMATERIALCOMMENT TEXT,
   BUILDINGSEWERDISTANCEFROMPRIVATE INTEGER,
   BUILDINGSEWERCOMMENTS TEXT,
   SEPTICTANKDEPTHBELOWGRADE INTEGER,
   SEPTICTANKMATERIAL INTEGER,
   SEPTICTANKMATERIALCOMMENT TEXT,
   SEPTICTANKMETALAGE INTEGER,
   SEPTICTANKCOMPLIANCE INTEGER,
   SEPTICTANKDIMENSIONS TEXT,
   SEPTICTANKSLUDGEDEPTH INTEGER,
   SEPTICTANKDISTANCEFROMTOPOFSLUDGE INTEGER,
   SEPTICTANKSCUMTHICKNESS INTEGER,
   SEPTICTANKDISTANCEFROMTOPOFSCUM INTEGER,
   SEPTICTANKDISTANCEFROMBOTTOMOFSCUM INTEGER,
   SEPTICTANKDIMENSIONSOBTAINED TEXT,
   SEPTICTANKCOMMENTS TEXT,
   GREASETRAPDEPTHBELOWGRADE INTEGER,
   GREASETRAPMATERIAL INTEGER,
   GREASETRAPMATERIALCOMMENT TEXT,
   GREASETRAPDIMENSIONS TEXT,
   GREASETRAPSCUMTHICKNESS INTEGER,
   GREASETRAPDISTANCEFROMTOPOFSCUM INTEGER,
   GREASETRAPDISTANCEFROMBOTTOMOFSCUM INTEGER,
   GREASETRAPDATEOFLASTPUMPING INTEGER,
   GREASETRAPCOMMENTS TEXT,
   TIGHTORHOLDINGTANKDEPTHBELOWGRADE INTEGER,
   TIGHTORHOLDINGTANKMATERIAL INTEGER,
   TIGHTORHOLDINGTANKMATERIALCOMMENT TEXT,
   TIGHTORHOLDINGTANKDIMENSIONS TEXT,
   TIGHTORHOLDINGTANKCAPACITY INTEGER,
   TIGHTORHOLDINGTANKDESIGNFLOW INTEGER,
   TIGHTORHOLDINGTANKALARMPRESENT INTEGER,
   TIGHTORHOLDINGTANKALARMLEVEL TEXT,
   TIGHTORHOLDINGTANKALARMWORKING INTEGER,
   TIGHTORHOLDINGTANKDATEOFLASTPUMPING INTEGER,
   TIGHTORHOLDINGTANKCOMMENTS TEXT,
   DISTRIBUTIONBOXDEPTHOFLIQUID INTEGER,
   DISTRIBUTIONBOXCOMMENTS TEXT,
   PUMPCHAMBERPUMPSWORK INTEGER,
   PUMPCHAMBERALARMWORK INTEGER,
   PUMPCHAMBERCOMMENTS TEXT,
   SOILABSORPTIONSYSTEMCOMMENTS INTEGER,
   SOILABSORPTIONLEACHINGPITS INTEGER,
   SOILABSORPTIONLEACHINGPITSNUMBER INTEGER,
   SOILABSORPTIONLEACHINGCHAMBERS INTEGER,
   SOILABSORPTIONLEACHINGCHAMBERSNUMBER INTEGER,
   SOILABSORPTIONLEACHINGGALLERIES INTEGER,
   SOILABSORPTIONLEACHINGGALLERIESNUMBER INTEGER,
   SOILABSORPTIONLEACHINGTRENCHES INTEGER,
   SOILABSORPTIONLEACHINGTRENCHESNUMBER INTEGER,
   SOILABSORPTIONLEACHINGTRENCHESLENGTH INTEGER,
   SOILABSORPTIONLEACHINGFIELDS INTEGER,
   SOILABSORPTIONLEACHINGFIELDSNUMBER INTEGER,
   SOILABSORPTIONLEACHINGFIELDSDIMENSION TEXT,
   SOILABSORPTIONOVERFLOWCESSPOOL INTEGER,
   SOILABSORPTIONOVERFLOWCESSPOOLNUMBER INTEGER,
   SOILABSORPTIONINNOVATIVE INTEGER,
   SOILABSORPTIONINNOVATIVENAME TEXT,
   SOILABSORPTIONCOMMENTS TEXT,
   CESSPOOLSNUMBER INTEGER,
   CESSPOOLSCONFIGURATION TEXT,
   CESSPOOLSDEPTHTOP INTEGER,
   CESSPOOLSDEPTHSOLID INTEGER,
   CESSPOOLSDEPTHSCUM INTEGER,
   CESSPOOLSDIMENSION TEXT,
   CESSPOOLSMATERIAL TEXT,
   CESSPOOLSINDICATIONOFGROUNDWATER INTEGER,
   CESSPOOLSCOMMENTS TEXT,
   PRIVYMATERIAL TEXT,
   PRIVYDIMENSIONS TEXT,
   PRIVYDEPTHOFSOLIDS INTEGER,
   PRIVYCOMMENTS TEXT,
   SITEEXAMCHECKSLOPE INTEGER,
   SITEEXAMSURFACEWATER INTEGER,
   SITEEXAMCHECKCELLAR INTEGER,
   SITEEXAMSHALLOWWELLS INTEGER,
   SITEEXAMDEPTHTOHIGHGROUNDWATER INTEGER,
   SITEEXAMMETHODSDESIGNPLANS INTEGER,
   SITEEXAMMETHODSDESIGNPLANSDATE INTEGER,
   SITEEXAMMETHODSOBSERVEDSITE INTEGER,
   SITEEXAMMETHODSCHECKEDWITHBOARDOFHEALTH INTEGER,
   SITEEXAMMETHODSCHECKEDWITHBOARDOFHEALTHCOMMENTS TEXT,
   SITEEXAMMETHODSCHECKEDWITHLOCALEXCAVATORS INTEGER,
   SITEEXAMMETHODSACCESSEDUSGS INTEGER,
   SITEEXAMMETHODSACCESSEDUSGSCOMMENTS TEXT,
   SITEEXAMDESCRIBE TEXT,
   REPORTCOMPLETENESSABCDE INTEGER,
   REPORTCOMPLETENESSD INTEGER,
   REPORTCOMPLETENESSSYSTEMINFORMATION INTEGER
);";

SUBSTRUCTURE140="CREATE TABLE DEPAPPROVAL(
    ID INTEGER PRIMARY KEY NOT NULL,
    OPTION TEXT NOT NULL
);";

SUBSTRUCTURE141="CREATE TABLE SYSTEMWILLPASSIF(
    ID INTEGER PRIMARY KEY NOT NULL,
    OPTION TEXT NOT NULL
);";

SUBSTRUCTURE142="CREATE TABLE SYSTEMWILLFAILIF(
    ID INTEGER PRIMARY KEY NOT NULL,
    OPTION TEXT NOT NULL
);";

SUBSTRUCTURE143="CREATE TABLE GENERALTYPEOFSYSTEM(
    ID INTEGER PRIMARY KEY NOT NULL,
    OPTION TEXT NOT NULL
);";

SUBSTRUCTURE144="CREATE TABLE BUILDINGSEWERMATERIAL(
    ID INTEGER PRIMARY KEY NOT NULL,
    OPTION TEXT NOT NULL
);";

SUBSTRUCTURE145="CREATE TABLE MATERIAL(
    ID INTEGER PRIMARY KEY NOT NULL,
    OPTION TEXT NOT NULL
);";

# Creating an Empty db file and filling it with my structure
echo $STRUCTURE0 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE1 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE2 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE3 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE4 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE5 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE6 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE7 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE8 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE9 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE10 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE11 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE12 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE13 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $STRUCTURE14 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE60 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE61 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE62 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE63 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE140 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE141 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE142 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE143 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE144 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
echo $SUBSTRUCTURE145 > /tmp/tmpstructure
sqlite3 $DBNAME < /tmp/tmpstructure;
rm -f /tmp/tmpstructure;

# Inserting some data into my structure
#sqlite3 dbname.db "INSERT INTO data (name,value) VALUES ('MyName','MyValue')";
#sqlite3 dbname.db "INSERT INTO data (name,value) VALUES ('MyOtherName','MyOtherValue')";

#Insert for type of operation in restaurant inspections
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Food Service')";
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Retail')";
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Residential Kitchen')";
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Mobile')";
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Temporary')";
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Caterer')";
sqlite3 $DBNAME "INSERT INTO TYPEOFOPERATION(OPERATIONTYPE) VALUES ('Bed & Breakfast')";

#Type of inspection inserts
sqlite3 $DBNAME "INSERT INTO TYPEOFINSPECTION(INSPECTIONTYPE) VALUES ('Routine')";
sqlite3 $DBNAME "INSERT INTO TYPEOFINSPECTION(INSPECTIONTYPE) VALUES ('Re-Inspection')";

#Reasoning

sqlite3 $DBNAME "INSERT INTO REASONING(REASONING) VALUES ('Pre-Operation')";
sqlite3 $DBNAME "INSERT INTO REASONING(REASONING) VALUES ('Suspect Illness')";
sqlite3 $DBNAME "INSERT INTO REASONING(REASONING) VALUES ('General Complaint')";
sqlite3 $DBNAME "INSERT INTO REASONING(REASONING) VALUES ('HACCP')";
sqlite3 $DBNAME "INSERT INTO REASONING(REASONING) VALUES ('Other')";

#Components (Septic Pumping Record)
sqlite3 $DBNAME "INSERT INTO SEPTICPUMPINGRECORD(OPTION) VALUES ('Cesspool')";
sqlite3 $DBNAME "INSERT INTO SEPTICPUMPINGRECORD(OPTION) VALUES ('Septic Tank')";
sqlite3 $DBNAME "INSERT INTO SEPTICPUMPINGRECORD(OPTION) VALUES ('Tight Tank')";
sqlite3 $DBNAME "INSERT INTO SEPTICPUMPINGRECORD(OPTION) VALUES ('Grease Trap')";
sqlite3 $DBNAME "INSERT INTO SEPTICPUMPINGRECORD(OPTION) VALUES ('Other')";

#Insert for DEPAPPROVAL
sqlite3 $DBNAME "INSERT INTO DEPAPPROVAL(OPTION) VALUES ('passes')";
sqlite3 $DBNAME "INSERT INTO DEPAPPROVAL(OPTION) VALUES ('conditionally passes')";
sqlite3 $DBNAME "INSERT INTO DEPAPPROVAL(OPTION) VALUES ('fails')";
sqlite3 $DBNAME "INSERT INTO DEPAPPROVAL(OPTION) VALUES ('needs further evaluation by the local approving authority')";

#Insert for SYSTEMWILLPASSIF
sqlite3 $DBNAME "INSERT INTO SYSTEMWILLPASSIF(OPTION) VALUES ('surface water')";
sqlite3 $DBNAME "INSERT INTO SYSTEMWILLPASSIF(OPTION) VALUES ('wetland')";

#Insert for SYSTEMWILLFAILIF
sqlite3 $DBNAME "INSERT INTO SYSTEMWILLFAILIF(OPTION) VALUES ('water supply')";
sqlite3 $DBNAME "INSERT INTO SYSTEMWILLFAILIF(OPTION) VALUES ('public water')";
sqlite3 $DBNAME "INSERT INTO SYSTEMWILLFAILIF(OPTION) VALUES ('private water')";

#Insert for GENERALTYPEOFSYSTEM
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('septic tank')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('single cesspool')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('overflow cesspool')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('privy')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('shared system')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('innovative/alternative system')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('tight tank')";
sqlite3 $DBNAME "INSERT INTO GENERALTYPEOFSYSTEM(OPTION) VALUES ('other')";

#Insert for BUILDINGSEWERMATERIAL
sqlite3 $DBNAME "INSERT INTO BUILDINGSEWERMATERIAL(OPTION) VALUES ('cast iron')";
sqlite3 $DBNAME "INSERT INTO BUILDINGSEWERMATERIAL(OPTION) VALUES ('PVC')";
sqlite3 $DBNAME "INSERT INTO BUILDINGSEWERMATERIAL(OPTION) VALUES ('other')";

#Insert for MATERIAL
sqlite3 $DBNAME "INSERT INTO MATERIAL(OPTION) VALUES ('concrete')";
sqlite3 $DBNAME "INSERT INTO MATERIAL(OPTION) VALUES ('metal')";
sqlite3 $DBNAME "INSERT INTO MATERIAL(OPTION) VALUES ('fiberglass')";
sqlite3 $DBNAME "INSERT INTO MATERIAL(OPTION) VALUES ('polyethylene')";
sqlite3 $DBNAME "INSERT INTO MATERIAL(OPTION) VALUES ('other')";

# Getting my data
# LIST=`sqlite3 $DBNAME "SELECT * FROM data WHERE 1"`;

# For each row
# for ROW in $LIST; do

#   # Parsing data (sqlite3 returns a pipe separated string)
#   Id=`echo $ROW | awk '{split($0,a,"|"); print a[1]}'`
#   Name=`echo $ROW | awk '{split($0,a,"|"); print a[2]}'`
#   Value=`echo $ROW | awk '{split($0,a,"|"); print a[3]}'`
  
#   # Printing my data
#   echo -e "\e[4m$Id\e[m) "$Name" -> "$Value;
  
# done










